# Generated by Django 5.2.16 on 2026-07-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0004_document_recipient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
    ]
